### ISSUE TITLE
IRQ_VECTORS conflict with MSDOS

### ISSUE THREAD

**Issue by keyvin** [SuperFabius/A250220_DEVEL#1]
I've been working on my port of MSDOS. Something kept overwriting the entry in the IVT I made. It took me many days to put two and two together that decimal 33 and 34 (lines 214 IRQ_VECTOR) work out to be .... wait for it... 21h and 22h. Two fairly important interrupt vectors in DOS. 

I've changed them to 0x40 (serial) and 0x41 (timer).

**Comment by SuperFabius** [comment]
The development revision **S260320-R260820_DEVEL2** contains all your changes (folder /DEVEL2).
